---
provider: "sqlite"

sqlite:
  path: "%data"
  name: "users.db"

mysqli:
  host: "127.0.0.1"
  username: "root"
  password: "password"
  name: "database"

registration:
  form:
    title: "Registration"
    label: "Label"
    input:
      text: "Text"
      placeholder: "Placeholder"
      default: "Default"
    success: "Success"
...